In [1]:
import sys
sys.path.append('..')

import pandas as pd
import numpy as np 

import torch
from torch.utils.data import Dataset, TensorDataset, DataLoader

import dill as pickle
from pathlib import Path

import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from utils import DatasetStandarsScaler

In [2]:
df = pd.read_csv('../../data/UCI_telescope/magic04.data', header=None)

In [3]:
df.loc[:, 10].replace({"g": 1, "h": 0}, inplace=True)

In [4]:
df.head()

0         1       2       3       4         5        6        7   \
0   28.7967   16.0021  2.6449  0.3918  0.1982   27.7004  22.0110  -8.2027   
1   31.6036   11.7235  2.5185  0.5303  0.3773   26.2722  23.8238  -9.9574   
2  162.0520  136.0310  4.0612  0.0374  0.0187  116.7410 -64.8580 -45.2160   
3   23.8172    9.5728  2.3385  0.6147  0.3922   27.2107  -6.4633  -7.1513   
4   75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277  28.5525  21.8393   

        8         9   10  
0  40.0920   81.8828   1  
1   6.3609  205.2610   1  
2  76.9600  256.7880   1  
3  10.4490  116.7370   1  
4   4.6480  356.4620   1

In [5]:
X, Y = np.asarray(df.loc[:, :9]), np.asarray(df.loc[:, 10])

In [6]:
x_tr, x_test, y_tr, y_test = train_test_split(X, Y, test_size=0.1)

In [7]:
clf = LogisticRegression(random_state=0, penalty='l2', C=1./8).fit(x_tr, y_tr)
(clf.predict(x_test) == y_test).sum() / y_test.shape[0]

0.7949526813880127

In [8]:
tr_dataset = []
for x, y in zip(x_tr, y_tr):
    tr_dataset.append((torch.tensor(x).float(), torch.tensor(y).long()))

test_dataset = []
for x, y in zip(x_test, y_test):
    test_dataset.append((torch.tensor(x).float(), torch.tensor(y).long()))

In [9]:
scaler = DatasetStandarsScaler()
scaler.fit(tr_dataset)

In [10]:
tr_dataset = scaler.transform(tr_dataset)
test_dataset = scaler.transform(test_dataset)

In [11]:
scaler = DatasetStandarsScaler()
scaler.fit(tr_dataset)

In [14]:
with Path('../../data/UCI_telescope/tr_dataset.pkl').open('wb') as fp:
    pickle.dump(tr_dataset, fp)

with Path('../../data/UCI_telescope/test_dataset.pkl').open('wb') as fp:
    pickle.dump(test_dataset, fp)

In [15]:
train_loader = DataLoader(tr_dataset, batch_size=3)

In [16]:
x, y = next(iter(train_loader))

In [17]:
x

tensor([[ 0.2210, -0.1252,  0.3556, -0.8831, -0.8789,  1.0611,  0.6481,  0.5907,
         -0.9689,  0.3059],
        [ 0.9572, -0.0591,  1.0591, -0.9749, -1.0200,  1.0628,  1.9190,  0.7679,
         -0.8906,  0.8168],
        [ 0.0881, -0.2130,  1.1236, -0.8668, -0.9232,  0.8191,  0.5798, -0.4339,
         -0.9699,  0.4350]])

In [2]:
df = pd.read_csv('../../data/UCI_EEG/dataset.csv', header=None)

In [3]:
df.head()

0        1        2        3        4        5        6        7   \
0  4329.23  4009.23  4289.23  4148.21  4350.26  4586.15  4096.92  4641.03   
1  4324.62  4004.62  4293.85  4148.72  4342.05  4586.67  4097.44  4638.97   
2  4327.69  4006.67  4295.38  4156.41  4336.92  4583.59  4096.92  4630.26   
3  4328.72  4011.79  4296.41  4155.90  4343.59  4582.56  4097.44  4630.77   
4  4326.15  4011.79  4292.31  4151.28  4347.69  4586.67  4095.90  4627.69   

        8        9        10       11       12       13  14  
0  4222.05  4238.46  4211.28  4280.51  4635.90  4393.85   0  
1  4210.77  4226.67  4207.69  4279.49  4632.82  4384.10   0  
2  4207.69  4222.05  4206.67  4282.05  4628.72  4389.23   0  
3  4217.44  4235.38  4210.77  4287.69  4632.31  4396.41   0  
4  4210.77  4244.10  4212.82  4288.21  4632.82  4398.46   0

In [4]:
X, Y = np.asarray(df.loc[:, :13]), np.asarray(df.loc[:, 14])
x_tr, x_test, y_tr, y_test = train_test_split(X, Y, test_size=0.15)

In [21]:
tr_dataset = []
for x, y in zip(x_tr, y_tr):
    tr_dataset.append((torch.tensor(x).float(), torch.tensor(y).long()))

test_dataset = []
for x, y in zip(x_test, y_test):
    test_dataset.append((torch.tensor(x).float(), torch.tensor(y).long()))


In [28]:
scaler = DatasetStandarsScaler()
scaler.fit(tr_dataset)

In [29]:
tr_dataset = scaler.transform(tr_dataset)
test_dataset = scaler.transform(test_dataset)

In [30]:
caler = DatasetStandarsScaler()
scaler.fit(tr_dataset)
print(scaler.mean, scaler.std)

tensor([ 1.7936e-08,  3.1409e-08, -9.6661e-08, -8.7989e-08,  3.9585e-10,
        -3.7368e-09,  1.2283e-08, -2.2446e-09,  1.2820e-07,  1.1848e-08,
        -2.4447e-07, -8.9526e-10, -7.0873e-08, -1.9701e-08]) tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [31]:
with Path('../../data/UCI_EEG/tr_dataset.pkl').open('wb') as fp:
    pickle.dump(tr_dataset, fp)

with Path('../../data/UCI_EEG/test_dataset.pkl').open('wb') as fp:
    pickle.dump(test_dataset, fp)

In [32]:
train_loader = DataLoader(tr_dataset, batch_size=3)
x, y = next(iter(train_loader))

In [33]:
x

tensor([[ 0.0222,  1.2415,  1.6496,  2.3576,  2.2347,  0.0117,  2.0172,  1.7829,
          0.0148,  1.7961,  1.3611,  1.5701,  0.0437,  0.0024],
        [-0.0153, -0.3291, -0.2520, -0.8619, -0.1763, -0.0138, -0.2810, -0.5600,
         -0.0115, -0.1523, -0.1039, -0.0245,  0.0061, -0.0099],
        [-0.0186, -0.5037, -0.1482, -0.6254, -0.6133, -0.0112, -0.3112,  0.1311,
         -0.0102,  0.3723, -0.1613,  0.0574, -0.0151, -0.0111]])

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
clf = LogisticRegression(random_state=0, penalty='l2', C=1./13).fit(x_tr, y_tr)


In [10]:
(clf.predict(x_test) == y_test).sum() / y_test.shape[0]

0.6350689808633734

In [11]:
(clf.predict(x_tr) == y_tr).sum() / y_tr.shape[0]

0.6366135239142386

In [3]:
import torch
from torch import nn 

class MyModel(nn.Module):
    def __init__(self, r):
        super().__init__()
        self.r=r
        self.linear = nn.Linear(10, 10)
    def forward(self, x):
        return self.linear(x)

In [7]:
from sklearn.preprocessing import StandardScaler

In [5]:
X, Y = np.asarray(df.loc[:, :13]), np.asarray(df.loc[:, 14])

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X)

StandardScaler()

In [12]:
scaler.mean_

array([4321.91777704, 4009.76769359, 4264.02243258, 4164.94632644,
       4341.74107543, 4644.02237917, 4110.40015955, 4616.05690387,
       4218.82661015, 4231.3161996 , 4202.45689987, 4279.23277437,
       4615.20533556, 4416.43583244])

In [13]:
scaler.var_

array([6.21000914e+06, 2.11049637e+03, 1.97372002e+03, 2.72090608e+07,
       1.20670511e+03, 8.55382278e+06, 2.11671119e+07, 8.57999322e+02,
       4.56393669e+06, 1.44777454e+03, 1.42768508e+03, 1.72581460e+03,
       1.46006048e+06, 3.47049225e+07])

In [5]:
X, Y = np.array(X), np.array(Y)

In [37]:
X.mean(1).shape

(14980,)

In [47]:
X_centr = X - X.mean(0)
covariance = (X_centr.transpose() @ X_centr)

X_norm = X_centr @ (covariance / X.shape[0])**(-0.5)

In [79]:
from torch.utils.data import TensorDataset, Dataset, DataLoader
from torchvision import transforms, datasets

Path('../../data').mkdir(exist_ok=True, parents=True)
trainset = datasets.MNIST(root='../../data', train=True, download=True, transform=transforms.ToTensor())
valset = datasets.MNIST(root='../../data', train=False, download=True, transform=transforms.ToTensor())

In [80]:
len(trainset)

60000

In [83]:
trainset[0][0].shape

torch.Size([1, 28, 28])

In [76]:
DataLoader(trainset).dataset[0][0]

In [68]:
TensorDataset?

Init signature: TensorDataset(*tensors)
Docstring:     
Dataset wrapping tensors.

Each sample will be retrieved by indexing tensors along the first dimension.

Arguments:
    *tensors (Tensor): tensors that have the same size of the first dimension.
File:           ~/.local/lib/python3.8/site-packages/torch/utils/data/dataset.py
Type:           type
Subclasses:     
